// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "../../app.config";
import type { default as appConfig1 } from "../../../../node_modules/.pnpm/@nuxt-themes+typography@0.11.0_magicast@0.5.2_postcss@8.5.9_vue@3.5.32_typescript@5.9.2_/node_modules/@nuxt-themes/typography/app.config";
import type { default as appConfig2 } from "../../../../node_modules/.pnpm/@nuxt-themes+elements@0.9.5_magicast@0.5.2_postcss@8.5.9_vue@3.5.32_typescript@5.9.2_/node_modules/@nuxt-themes/elements/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1, typeof appConfig2]>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}

}
export {}