// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/search': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt-themes+docus@1.15.1_change-case@4.1.2_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@4.4._tmcacw5hryfidpt7jgxgklthie/node_modules/@nuxt-themes/docus/server/api/search').default>>>>
    }
    '/opensearch.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt-themes+docus@1.15.1_change-case@4.1.2_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@4.4._tmcacw5hryfidpt7jgxgklthie/node_modules/@nuxt-themes/docus/server/routes/opensearch.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@4.4.2_@babel+core@7.29.0_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@4.4._oq2xcvdpoooibgfho2epbwish4/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/__studio.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxthq+studio@2.2.1_magicast@0.5.2/node_modules/@nuxthq/studio/dist/runtime/server/routes/studio').default>>>>
    }
    '/api/component-meta': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-component-meta@0.9.0_magicast@0.5.2/node_modules/nuxt-component-meta/dist/runtime/server/api/component-meta.get').default>>>>
    }
    '/api/component-meta.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-component-meta@0.9.0_magicast@0.5.2/node_modules/nuxt-component-meta/dist/runtime/server/api/component-meta.get').default>>>>
    }
    '/api/component-meta/:component?': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-component-meta@0.9.0_magicast@0.5.2/node_modules/nuxt-component-meta/dist/runtime/server/api/component-meta.get').default>>>>
    }
    '/api/_mdc/highlight': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxtjs+mdc@0.9.5_magicast@0.5.2/node_modules/@nuxtjs/mdc/dist/runtime/highlighter/event-handler').default>>>>
    }
    '/api/_content/query/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@4.4.2_@babel+core@7.29.0_@b_novdd57ebcljgswbgzsxdmb3uy/node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@4.4.2_@babel+core@7.29.0_@b_novdd57ebcljgswbgzsxdmb3uy/node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@4.4.2_@babel+core@7.29.0_@b_novdd57ebcljgswbgzsxdmb3uy/node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/cache.1776004351139.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@4.4.2_@babel+core@7.29.0_@b_novdd57ebcljgswbgzsxdmb3uy/node_modules/@nuxt/content/dist/runtime/server/api/cache').default>>>>
    }
    '/api/_content/navigation/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@4.4.2_@babel+core@7.29.0_@b_novdd57ebcljgswbgzsxdmb3uy/node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@4.4.2_@babel+core@7.29.0_@b_novdd57ebcljgswbgzsxdmb3uy/node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nuxt@4.4.2_@babel+core@7.29.0_@b_novdd57ebcljgswbgzsxdmb3uy/node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
  }
}
export {}